=== Smet1/prdb/hw/db.dtd
<!ELEMENT mydb (user|post|tag)*>
<!ELEMENT user (id|about|karma|avatar|password|login|first_name|last_name|middle_name)*>
<!ATTLIST user
        idu CDATA #REQUIRED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT about (#PCDATA)>
<!ELEMENT karma (#PCDATA)>
<!ELEMENT avatar (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT post (id|header|short_topic|main_topic|date)*>
<!ATTLIST post
        idp CDATA #REQUIRED
        tot CDATA #REQUIRED
        tou CDATA #REQUIRED>
<!ELEMENT header (#PCDATA)>
<!ELEMENT short_topic (#PCDATA)>
<!ELEMENT main_topic (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT tag (id|name)*>
<!ATTLIST tag
        idt CDATA #REQUIRED
        top CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>

=== Smet1/prdb/hw/model.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE mydb SYSTEM "db.dtd">
<mydb>
    <user idu="u1">
        <id>1</id>
        <about>Обо мне</about>
        <karma>0</karma>
        <avatar>/static/default.png</avatar>
        <password>empty</password>
        <login>a.petrov</login>
        <first_name>Андрей</first_name>
        <last_name>Петров</last_name>
        <middle_name>Андреевич</middle_name>
    </user>

    <post idp="p1" tot="t1" tou="u1">
        <id>1</id>
        <header>header</header>
        <short_topic>short topic about post</short_topic>
        <main_topic>main topic</main_topic>
        <date>05.04.2010</date>
    </post>

    <tag idt="t1" top="p1">
        <id>1</id>
        <name>pbd</name>
    </tag>
</mydb>
